project:
  type: website
  output-dir: docs

website:
  title: "Laura Furtado Fernandes"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - text: "Data Viz"
        menu: 
          - text: "Hollywood Age Gaps"
            href: viz1.html  
          - text: "Valentines Gift Habits"
            href: viz2.html 
      - text: "Mini Projects"
        menu:     
          - text: "Project 2"
            href: project2.html
          - text: "Project 3"
            href: project3.html
          - text: "Project 4"
            href: project4.html
            
          
format:
  html:
    theme: 
      light: pulse
      dark: darkly
    css: styles.css
    toc: true
    page-layout: full

editor: visual

