project:
  type: website
  output-dir: docs

website:
  title: "Laura Furtado Fernandes"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: about.qmd
        text: "About"
      - text: "Data Viz"
        menu: 
          - text: "Viz 1"
            href: viz1.html 
            
     
format:
  html:
    theme: 
      light: quartz
      dark: vapor
    css: styles.css
    toc: true
    page-layout: full

editor: visual

