---
title: "Data Science Ethics"
description: |
 The Facebook Problem
author: Laura Furtado Fernandes
date: April 16, 2025
format:
  html:
    code-fold: true
    code-summary: "Show the code"
execute:
  error: false  
  warning: false
---

**Facebook Ethical Dilemma**

In 2014, a paper titled '[Experimental Evidence of Massive-Scale Emotional Contagion through Social Networks](https://www.pnas.org/doi/10.1073/pnas.1320040111)' was published in *Proceedings of the National Academy of Sciences of the United States of America* (Kramer et al., 2014). This paper details the results from a large-scale experiment conducted on 689,003 English-speaking Facebook users to examine how the valence (positive or negative) of their News Feed content influenced their behavior on Facebook over a period of 1 week. Specifically, they measured whether people who saw differently valenced News Feeds used different percentages of positive vs negative words in their posts. This research, however, became highly controversial because it seemingly ignored pillars of academic investigation and data science, like informed consent, ethical data collection, improving lives, data transparency and availability, and generalizability.

**Informed Consent Violations**

Firstly, in order to do this research and observe emotion contagion, the researchers manipulated users' news feeds and, in essence, experimented on them without their informed consent. Participants were recruited and randomly assigned to conditions without being informed of participation in the study (Kramer et al. 2014). There are obvious ethical issues with this, as manipulating participants without their consent goes against the Belmont Report's guidelines for research on human participants (National Commission, 1979). Some argued that this sort of research is commonplace in industry (Park, 2014; Boesel, 2014) and that it only became unethical when it was published and fell short of the moral standards expected of academics (Park, 2014). Especially since it was done in collaboration with Cornell University: the Facebook researcher, Adam Kramer, partnered with two Cornell University investigators, Jamie Guillory and Jeffrey Hancock, in this project. The Cornell Institutional Review Board deemed the study exempt from their oversight because the data was being collected by Facebook, and some argue that it was a mistake (Boesel, 2014). This study violated the informed consent and ethical data collection principles of data science research.

**Failure to Improve Lives**

The Facebook emotional contagion study also violated the data science principle that data should be used to improve the lives of individuals and communities. One could argue that this research is valuable and that the findings are beneficial to humanity because understanding emotional contagion is important and that this was the only way to study emotional contagion. However, that is not entirely true. Emotion contagion had been studied in more naturalistic ways years before Kramer et al. (2014) did it. Fowler & Christakis (2008) studied emotion contagion in social networks over a period of 20 years, 4739 participants consented to participate in a study; they found that there are clusters of happy and unhappy people in social networks and that happiness spread through the network, if a friend who lives within a mile becomes happy, it increases the probability that a person is happy by 25%. You could then argue that this effect is understudied in social media and that this was the only way to accurately do that, and that would also not be entirely true. One year after Kramer et al. (2014) published their study, and in response to the controversy, Ferrara and Yang (2015) investigated emotional contagion in social media by observing people on Twitter and measuring the valence of the content they had been exposed to without manipulating it. Therefore, the Facebook study not only introduced ethical harm (via emotional manipulation without consent) but also failed to generate new insights that justified those harms.

**Lack of Transparency**

Additionally, if this research had truly been revolutionary and overwhelmingly beneficial to others, then it stands to reason that the data collected in this study should be made publicly available and transparent which was not the case (Kramer et al., 2014). Instead, interested parties could reach out to Kramer et al. to request access to the data. This limits the work's reproducibility and extension of the findings, violating data science principles.

**Generalizability and Bias**

Furthermore, this research was conducted solely with English-speaking individuals who use Facebook, which raises concerns about cross-culture generalizability (Kramer et al., 2014). Then, can we claim that the findings are generalized to all of humanity? Or just to English-speaking, rich, industrialized populations? In this case, this research and findings are also perpetuating issues in the field of behavioral science, like the over-representation of WEIRD populations (Apa.Org, 2025). Given the access that Facebook had, they should and could have made this research more inclusive.

**References:**

*Are your findings “WEIRD”?* (n.d.). Https://Www.Apa.Org. Retrieved April 16, 2025, from <https://www.apa.org/monitor/2010/05/weird>

Boesel, W. E. (2014, July 3). *Facebook’s Controversial Experiment: Big Tech Is the New Big Pharma*. TIME. <https://time.com/2951726/facebook-emotion-contagion-experiment/>

Fowler, J. H., & Christakis, N. A. (2008). Dynamic spread of happiness in a large social network: Longitudinal analysis over 20 years in the Framingham Heart Study. *BMJ (Clinical Research Ed.)*, *337*, a2338. <https://doi.org/10.1136/bmj.a2338>

Ferrara, E., & Yang, Z. (2015). Measuring Emotional Contagion in Social Media. *PLOS ONE*, *10*(11), e0142390. <https://doi.org/10.1371/journal.pone.0142390>

Kramer, A. D., Guillory, J. E., and Hancock, J. T. (2014), [Experimental Evidence of Massive-Scale Emotional Contagion through Social Networks](https://www.pnas.org/doi/10.1073/pnas.1320040111), Proceedings of the National Academy of Sciences of the United States of America, 111, 8788–8790

Park, A. (2014, June 30). *Calm Down: Facebook Isn’t Really Manipulating Your Emotions*. TIME. <https://time.com/2941513/calm-down-facebook-isnt-manipulating-your-emotions/>

National Commission for the Protection of Human Subjects of Biomedical and Behavioral Research. (1979). *The Belmont report: Ethical principles and guidelines for the protection of human subjects of research*. U.S. Department of Health and Human Services. <https://www.hhs.gov/ohrp/regulations-and-policy/belmont-report/read-the-belmont-report/index.html>
